### ISSUE TITLE
随机到重复网站几率很大

### ISSUE THREAD

**Issue by mymutouren** [passerby-cn/passerby-cn.github.io#1]
试用了一下网站，有个问题就是随机到重复网站的几率很大，导致瞬间就不期待了

**Comment by mumuy** [comment]
哈哈哈，就是玩玩，收集的站点不够多

**Comment by mymutouren** [comment]
我觉得想法还是挺好的．回头有机会合作下把它搞上线运营试试．

**Comment by mymutouren** [comment]
您好，我想加个默认的主页，每次打开域名显示这个主页，点＂随意＂才开始进行随机，请问这个怎么实现呢

**Comment by mumuy** [comment]
我现在的就是，有一个主页，设置了cookie，如果两个小时没刷新过就显示出来……你可以把它改短一点

**Comment by mymutouren** [comment]
您好，我把您的随机导航网站和我原来的网站做了一个结合，域名是：www.yiijj.com，其中的主页是我原来的导航页面，我想让它默认作为主页，您原来的主页我还想保留作为超时的操作提示．我qq:61102610

**Comment by mumuy** [comment]
你不觉得需求很矛盾么？都是一段时间没有刷新，则显示该页面。我那个页面不是超时提醒，是长时间不活动当成第一次登录
